I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 534, in script
    show b1_casual at -0.3 with dissolve
TypeError: 'float' object is not callable

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/script.rpy", line 534, in script
    show b1_casual at -0.3 with dissolve
  File "renpy/ast.py", line 1357, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/ast.py", line 730, in show_imspec
    renpy.config.show(
    ~~~~~~~~~~~~~~~~~^
        name, at_list=at_list, layer=layer, what=expression, zorder=zorder, tag=tag, behind=behind, atl=atl
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "renpy/exports/displayexports.py", line 498, in show
    img = i(img)  # type: ignore
          ~^^^^^                
TypeError: 'float' object is not callable

Windows-11-10.0.22000-SP0 AMD64
Ren'Py 8.4.1.25072401
HAVENT FINISH DIARY 1.0
Sun Sep 28 03:02:54 2025
